<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Digital Dentistry & Exocad Workflow | YZH Dental Lab</title>
<meta name="description" content="Exocad design, digital file review, design approval and CAD/CAM manufacturing support for overseas dental laboratories.">
<link rel="canonical" href="https://yzhdentallab.com/digital-dentistry"><link rel="icon" href="/favicon.svg" type="image/svg+xml">
<meta property="og:type" content="website"><meta property="og:url" content="https://yzhdentallab.com/digital-dentistry"><meta property="og:title" content="Digital Dentistry & Exocad Workflow | YZH Dental Lab"><meta property="og:description" content="Design-only and design-plus-manufacturing support for digital dental workflows."><meta property="og:image" content="https://yzhdentallab.com/assets/real/full-arch-cad-design-05.jpg">
<link rel="stylesheet" href="/assets/site.css?v=professional-1">
</head>
<body>
<header class="site-header"><div class="wrap nav"><a class="brand" href="/"><img class="brand-logo" src="/assets/brand/yzh-mark.svg" alt=""><span>YZH Dental Lab</span></a><button class="menu-toggle" type="button" aria-controls="primaryNav" aria-expanded="false">Menu</button><nav class="navlinks" id="primaryNav"><a href="/">Home</a><a href="/cases">Cases</a><a href="/about">About</a></nav><a class="btn btn-primary nav-cta" href="/submit-case">Send a Trial Case</a></div></header>
<main>
  <section class="page-hero"><div class="wrap page-hero-grid"><div><p class="eyebrow">Digital Dentistry / CAD-CAM</p><h1>Exocad Design and Digital Production Support</h1><p class="lead">Digital file review, Exocad design communication and CAD/CAM production support for implant, full-arch and restorative cases.</p><div class="cta-row"><a class="btn btn-primary" href="/submit-case">Send Digital Files</a><a class="btn btn-green" href="https://wa.me/8613714730109" target="_blank" rel="noopener noreferrer">WhatsApp Technical Team</a></div></div><img src="/assets/real/full-arch-cad-design-05.jpg" alt="Exocad full-arch CAD design view" width="1600" height="900" loading="eager" fetchpriority="high"></div></section>
  <section class="section"><div class="wrap two-col"><div><p class="eyebrow">Files & Records</p><h2>Send the records available for the case.</h2><p class="copy">The submission workflow accepts STL, PLY, ZIP, PDF, JPG, JPEG and PNG. Include the prescription, implant information when relevant, shade, photos and approval requirements. Large CBCT or DICOM datasets should be placed in a ZIP or shared through a secure link in the case message.</p><ul class="check-list"><li>STL or PLY scans</li><li>Prescription and restoration request</li><li>Implant system, platform and scanbody information</li><li>Reference photos and shade information</li><li>Existing design or provisional records when available</li></ul></div><div><p class="eyebrow">Two Support Modes</p><div class="proof-list"><article><h3>Design Only</h3><p>YZH prepares the agreed CAD design and shares approval information for the partner lab's production workflow.</p></article><article><h3>Design + Manufacturing</h3><p>After design approval, the case continues through the confirmed CAD/CAM production, finishing and QC workflow.</p></article></div></div></div></section>
  <section class="section soft"><div class="wrap"><div class="section-head"><p class="eyebrow">Digital Workflow</p><h2>One technical path from file check to delivery.</h2></div><div class="steps informational-steps"><article><span>01</span><h3>File Check</h3><p>Files and required case information are reviewed.</p></article><article><span>02</span><h3>Exocad Design</h3><p>The restoration is designed around the confirmed records.</p></article><article><span>03</span><h3>Design Approval</h3><p>Design views are shared when approval is part of the requested workflow.</p></article><article><span>04</span><h3>Production</h3><p>Manufacturing begins only after the required details are clear.</p></article><article><span>05</span><h3>QC & Delivery</h3><p>Case details are checked and communicated before dispatch.</p></article></div></div></section>
  <section class="section trial"><div class="wrap two-col"><div><p class="eyebrow">Technical Case Review</p><h2>Start with one digital case.</h2><p class="copy">Tell us whether you need design only or design plus manufacturing, and include the files already available.</p></div><div class="cta-panel"><a class="btn btn-primary" href="/submit-case">Send Digital Files</a><a class="btn btn-green" href="https://wa.me/8613714730109" target="_blank" rel="noopener noreferrer">WhatsApp Technical Team</a></div></div></section>
</main>
<footer class="site-footer"><div class="wrap"><p>YZH Dental Lab</p></div></footer><script src="/assets/site.js?v=professional-1" defer></script>
</body></html>
