<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Surgical Guide Design & Production Support | YZH Dental Lab</title>
<meta name="description" content="Surgical guide design and printed guide support using STL or PLY surface scans, CBCT data, implant system and sleeve information.">
<link rel="canonical" href="https://yzhdentallab.com/surgical-guides"><link rel="icon" href="/favicon.svg" type="image/svg+xml">
<meta property="og:type" content="website"><meta property="og:url" content="https://yzhdentallab.com/surgical-guides"><meta property="og:title" content="Surgical Guide Design & Production Support | YZH Dental Lab"><meta property="og:description" content="Clear records and implant component information for surgical guide workflows."><meta property="og:image" content="https://yzhdentallab.com/assets/real/surgical-guide-workflow-poster-03.jpg">
<link rel="stylesheet" href="/assets/site.css?v=professional-1">
</head>
<body>
<header class="site-header"><div class="wrap nav"><a class="brand" href="/"><img class="brand-logo" src="/assets/brand/yzh-mark.svg" alt=""><span>YZH Dental Lab</span></a><button class="menu-toggle" type="button" aria-controls="primaryNav" aria-expanded="false">Menu</button><nav class="navlinks" id="primaryNav"><a href="/">Home</a><a href="/cases">Cases</a><a href="/about">About</a></nav><a class="btn btn-primary nav-cta" href="/submit-case">Send a Trial Case</a></div></header>
<main>
  <section class="page-hero"><div class="wrap page-hero-grid"><div><p class="eyebrow">Surgical Guides</p><h1>Surgical Guide Support with Clear File Review</h1><p class="lead">Design-only and printed guide workflows based on the submitted surface scans, CBCT data, implant plan and sleeve information.</p><div class="cta-row"><a class="btn btn-primary" href="/submit-case">Send Guide Records</a><a class="btn btn-green" href="https://wa.me/8613714730109" target="_blank" rel="noopener noreferrer">WhatsApp Technical Team</a></div></div><img src="/assets/real/surgical-guide-workflow-poster-03.jpg" alt="Digital surgical guide design workflow at YZH Dental Lab" width="1600" height="900" loading="eager" fetchpriority="high"></div></section>
  <section class="section"><div class="wrap two-col"><div><p class="eyebrow">What To Send</p><h2>Records needed for a useful guide review.</h2><ul class="check-list"><li>STL or PLY surface scan</li><li>CBCT data as DICOM files or a ZIP</li><li>Implant system and planned implant information</li><li>Sleeve type and sleeve dimensions when specified</li><li>Planning notes and restorative requirements</li></ul><p class="copy">The clinician remains responsible for diagnosis, implant position approval and patient treatment decisions.</p></div><div class="proof-list"><article><h3>Tooth-Supported Workflow</h3><p>Surface scan and CBCT alignment can be reviewed for tooth-supported guide work when complete records are provided.</p></article><article><h3>Implant & Sleeve Review</h3><p>Implant system, sleeve information and available planning records are checked before design approval.</p></article><article><h3>Design Only</h3><p>Guide design support for partner labs that will manage their own printing workflow.</p></article><article><h3>Design + Printed Guide</h3><p>Printed guide support when the submitted records and requested guide workflow are confirmed.</p></article></div></div></section>
  <section class="section soft"><div class="wrap"><div class="section-head"><p class="eyebrow">Workflow</p><h2>Review first, then design and production.</h2></div><div class="steps informational-steps"><article><span>01</span><h3>Record Check</h3><p>Surface scans, CBCT data and case instructions are reviewed.</p></article><article><span>02</span><h3>Planning Information</h3><p>Implant and sleeve details are confirmed.</p></article><article><span>03</span><h3>Guide Design</h3><p>The guide is designed around the approved plan and records.</p></article><article><span>04</span><h3>Approval</h3><p>Required design communication is completed before production.</p></article><article><span>05</span><h3>Print & QC</h3><p>Printed guide workflow proceeds when requested and confirmed.</p></article></div></div></section>
  <section class="section trial"><div class="wrap two-col"><div><p class="eyebrow">Start With One Case</p><h2>Send the available guide records.</h2><p class="copy">ZIP large DICOM datasets or include a secure file-sharing link in the case message.</p></div><div class="cta-panel"><a class="btn btn-primary" href="/submit-case">Send Guide Records</a><a class="btn btn-green" href="https://wa.me/8613714730109" target="_blank" rel="noopener noreferrer">WhatsApp Technical Team</a></div></div></section>
</main>
<footer class="site-footer"><div class="wrap"><p>YZH Dental Lab</p></div></footer><script src="/assets/site.js?v=professional-1" defer></script>
</body></html>
